### ISSUE TITLE
Trailing commas in arguments are invalid for binding patterns or rest parameters

### ISSUE THREAD

**Issue by kitsonk** [dsherret/dprint#163]
The current version of dprint, when allow trailing commas in arguments, adds them in syntatically invalid locations.  For example:

```ts
function foo(
  a: A,
  b: B,
  ...c: C
): void { }
```

Cannot be reformatted to:

```ts
function foo(
  a: A,
  b: B,
  ...c: C,
): void { }
```

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#Illegal_trailing_commas
Ref: #153

**Comment by dsherret** [comment]
Ugh! I remember reading this on the weekend and then forgetting about it.

Thanks @kitsonk! Fixed and published in 0.9.6. Also it was missing trailing commas in object patterns so that's fixed now too.

See test file for illegal trailing commas here to make sure I didn't miss something: https://github.com/dsherret/dprint/blob/9e04af06266c98ad0d392237e40cc007247b0f5b/packages/rust-dprint-plugin-typescript/tests/specs/common/configuration/IllegalTrailingCommas.txt
